_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

oc_platform_translation:
    path: /{_locale}/traduction/{name}
    defaults: { _controller: "OCPlatformBundle:Advert:translation" }

oc_platform_paramconverter:
    path: /test/{json}
    defaults: { _controller: "OCPlatformBundle:Advert:paramConverter" }

_console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    prefix: /_console

_main:
    resource: routing.yml
