# app/config/security.yml

security:
    encoders:
        OC\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: OC\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: /platform

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }


# dans le cas ou meme les annonymes ne sont pas autoriser, utiliser cette construction

#firewalls:
#    # On crée un pare-feu uniquement pour le formulaire
#    main_login:
#        # Cette expression régulière permet de prendre /login (mais pas /login_check !)
#        pattern:   ^/login$
#        anonymous: true # On autorise alors les anonymes sur ce pare-feu
#    main:
#        pattern:   ^/
#        anonymous: false
#        # ...